### ISSUE TITLE
냐냥!

### ISSUE THREAD

**Issue by U-siro** [HanbitGaram/brackets-config#2]
(또 어디선가 들어온 새로운 고양이.)

**Comment by U-siro** [comment]
(안 들켰다. 도망가자.)

**Comment by HanbitGaram** [comment]
미션 : 이슈에 들어온 **고양이를** 잡아라.

> 인생에서 고양이를 잡는것, 매우 보람.

**Comment by HanbitGaram** [comment]
고양이를 잡았으므로, 이슈를 닫습니다.
